# Gripper controller
gripper_controller:
  type: position_controllers/GripperActionController
  joint: finger_joint


gazebo_ros_control:
  pid_gains:
    right_outer_knuckle_joint:
      p: 50.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    left_inner_finger_joint:
      p: 50.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    right_inner_finger_joint:
      p: 50.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    left_inner_knuckle_joint:
      p: 50.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true      
    right_inner_knuckle_joint:
      p: 50.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true  
    finger_joint:
      p: 50.0
      i: 0.1
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
